name: Docker Compose Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-docker:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:26.0.0
        options: --privileged
    steps:
      - uses: actions/checkout@v2
      - name: Modify Dockerfile to disable USER www (which is not supported by GitHub Actions, as it runs as root)
        run: |
          sed -i '/USER www/s/^/#/' ./Dockerfile
      - name: Set Permissions
        run: sudo chmod -R 777 /var/www
      - name: Copy .env
        run: sudo cp .env.example .env
      - name: Set up Docker Compose
        run: |
          # Build the images and start the services
          docker compose -f docker-compose.yml up -d
      - name: Run Tests
        run: docker compose exec -T ogame-app php artisan test
      - name: Run custom Race Condition Tests
        run: |
          docker compose exec -T ogame-app php artisan test:race-condition-unitqueue
          docker compose exec -T ogame-app php artisan test:race-condition-game-mission